### ISSUE TITLE
UndefVarError: py_add_legend not defined

### ISSUE THREAD

**Issue by luca-rosa** [gszep/double-exclusive-reporter#19]
https://github.com/gszep/double-exclusive-reporter/blob/079ba3b2c8382bbccf075ecc58fb5378a4c5f6a4/main.jl#L40

Hi Gregg, I've tried to run the last commit but I get the error in the title when trying to generate the animation

**Comment by gszep** [comment]
try updating your julia packages enter a julia session, then press the `]` key to enter up the package manager. then type 
```
update
```

**Comment by gszep** [comment]
you mind need to recompile the plotting library after update
https://github.com/JuliaPlots/Plots.jl/issues/2255

**Comment by gszep** [comment]
but it seems to be an issue with communication between julia and pyplot library

**Comment by gszep** [comment]
@luca-rosa did updating solve the issue?

**Comment by luca-rosa** [comment]
Yes it's working now!
